### ISSUE TITLE
Check connection before trying to send commands

### ISSUE THREAD

**Issue by MCMainiac** [TheHolyWaffle/TeamSpeak-3-Java-API#132]
When I was debugging an application, I noticed that the api tried to send a command to a socket that wasn't open. Correct me if I'm wrong :D

```
21:41:27 [INFORMATION] [2016-08-29 21:41:27.082] [SEVERE] [Connection] Disconnected from TS3 server
21:41:27 [INFORMATION] [2016-08-29 21:41:27.084] [SEVERE] ConnectionHandler threw exception in disconnect handler
java.lang.NullPointerException
    at com.github.theholywaffle.teamspeak3.TS3Query.doCommand(TS3Query.java:162)
    at com.github.theholywaffle.teamspeak3.TS3Query.exit(TS3Query.java:125)
    at com.github.theholywaffle.teamspeak3.api.reconnect.DisconnectingConnectionHandler.onDisconnect(DisconnectingConnectionHandler.java:49)
    at com.github.theholywaffle.teamspeak3.TS3Query$2.run(TS3Query.java:208)
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
    at java.util.concurrent.FutureTask.run(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.lang.Thread.run(Unknown Source)
```

**Comment by rogermb** [comment]
Should hopefully be fixed in fd5b5a4b3238b34ecdceb6e24e113dfc80fa93fa. Let me know if there are any issues :smile:
