### ISSUE TITLE
Caused by: java.lang.ClassNotFoundException: com.github.theholywaffle.teamspeak3.TS3Config

### ISSUE THREAD

**Issue by ITDestroy** [TheHolyWaffle/TeamSpeak-3-Java-API#142]
I have an Problem with the Teamspeak API using Maven
=============================================
Here the ERROR Log
```
[11:32:22 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'ts' in plugin Minecron_Teamspeak v1.0
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[spigot.jar:git-Spigot-047f737-744e1a1]
at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot.jar:git-Spigot-047f737-744e1a1]
at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:647) ~[spigot.jar:git-Spigot-047f737-744e1a1]
at net.minecraft.server.v1_10_R1.PlayerConnection.handleCommand(PlayerConnection.java:1358) [spigot.jar:git-Spigot-047f737-744e1a1]
at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1193) [spigot.jar:git-Spigot-047f737-744e1a1]
at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [spigot.jar:git-Spigot-047f737-744e1a1]
at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [spigot.jar:git-Spigot-047f737-744e1a1]
at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [spigot.jar:git-Spigot-047f737-744e1a1]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_101]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_101]
at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [spigot.jar:git-Spigot-047f737-744e1a1]
at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:732) [spigot.jar:git-Spigot-047f737-744e1a1]
at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400) [spigot.jar:git-Spigot-047f737-744e1a1]
at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) [spigot.jar:git-Spigot-047f737-744e1a1]
at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [spigot.jar:git-Spigot-047f737-744e1a1]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: java.lang.NoClassDefFoundError: com/github/theholywaffle/teamspeak3/TS3Config
at de.minecron.Teamspeak.main.onCommand(main.java:22) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-047f737-744e1a1]
... 15 more
Caused by: java.lang.ClassNotFoundException: com.github.theholywaffle.teamspeak3.TS3Config
at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_101]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot.jar:git-Spigot-047f737-744e1a1]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot.jar:git-Spigot-047f737-744e1a1]
at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_101]
at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_101]
at de.minecron.Teamspeak.main.onCommand(main.java:22) ~[?:?]
at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[spigot.jar:git-Spigot-047f737-744e1a1]
... 15 more
>
```
================================================
Here my Class
```
package de.minecron.Teamspeak;

import com.github.theholywaffle.teamspeak3.TS3Api;
import com.github.theholywaffle.teamspeak3.TS3Config;
import com.github.theholywaffle.teamspeak3.TS3Query;
import org.bukkit.command.Command;
import org.bukkit.command.CommandExecutor;
import org.bukkit.command.CommandSender;
import org.bukkit.plugin.java.JavaPlugin;

import java.util.logging.Level;
public class main extends JavaPlugin implements CommandExecutor{
    public void onEnable() {}
    public void onDisable(){}

    @Override
    public boolean onCommand(CommandSender sender, Command cmd, String label, String[] args) {
        final TS3Config config = new TS3Config(); //Unser Config Objekt
        config.setHost("XXX.XXX.XXX.XXX"); //Die ServerIP
        config.setDebugLevel(Level.ALL); //Der DebugLevel (Gibt an wieviel in der Konsole angezeigt werden soll)

        final TS3Query query = new TS3Query(config);
        query.connect();

        final TS3Api api = query.getApi();
        api.login("XXXXXXX", "XXXXXX");
        api.selectVirtualServerById(1);
        api.setNickname("MC-Bot");
        api.sendChannelMessage("MC-Bot is online!");

        if (cmd.getName().equalsIgnoreCase("ts")) {
            if (args.length == 0) {
                sender.sendMessage("§7========== §3Teamspeak §7==========");
                sender.sendMessage("Test " + api.getVersion());
            }
        }
    return true;}
}
```
=================================
pom.xml Maven API
```
`        <repository>
            <id>TeamSpeak-3-Java-API-mvn-repo</id>
            <url>https://raw.githubusercontent.com/TheHolyWaffle/TeamSpeak-3-Java-API/mvn-repo/</url>
            <snapshots>
                <enabled>true</enabled>
                <updatePolicy>always</updatePolicy>
            </snapshots>
        </repository>

        <dependency>
            <groupId>com.github.theholywaffle</groupId>
            <artifactId>teamspeak3-api</artifactId>
            <version>[1.0.0,2.0.0)</version>
        </dependency>
```

**Comment by rogermb** [comment]
Heyo 😄 

This problem is due to you compiling against the TS3-Api as a dependency but failing to actually provide that library at runtime.

With the default settings, Maven will happily compile your program with the assumption that any required libraries will already be available on the classpath when you try to run your program. But of course, Bukkit / Spigot doesn't have our class files loaded, so you'll have to provide them on your own.

There are multiple ways you could do this:
- You could add the JAR file of our API to the plugins directory of your server. This is by far the easiest way to solve this, but it's probably also the worst one. For one, it makes your plugin harder to install and it could also cause other issues because this API isn't a valid Bukkit plugin
- Alternatively, you could include the classes of this API in your own JAR file by copying them over. There are multiple plugins that do this with Maven. The most popular ones are probably the [Shade plugin](https://maven.apache.org/plugins/maven-shade-plugin/index.html) and the [Assembly plugin](http://maven.apache.org/plugins/maven-assembly-plugin/index.html).
  
  The Shade plugin is likely easier to use and more suitable to the problem, but it usually leads to longer build times. The Assembly plugin usually runs a bit faster - if I remember correctly - but it's also less customizable than the Shade plugin. If build times aren't really that much of a concern to you, it's probably best to go with the Shade plugin.

I hope this clears up the issue :smile:

Thank you very much for including so much information in your issue report. It didn't really matter too much in this case as the problem is easy to spot, but I appreciate it nonetheless.
