### ISSUE TITLE
Teamspeak api crashes on inizalising

### ISSUE THREAD

**Issue by mlh1100** [TheHolyWaffle/TeamSpeak-3-Java-API#216]
So when i start my programm the api throws an error.
This is the error:
`Exception in thread "[TeamSpeak-3-Java-API] SocketWriter" java.lang.NullPointerException          
        at com.github.theholywaffle.teamspeak3.commands.CommandEncoding.encode(CommandEncoding.jav
a:34)                                                                                             
        at com.github.theholywaffle.teamspeak3.commands.parameter.KeyValueParam.build(KeyValuePara
m.java:55)                                                                                        
        at com.github.theholywaffle.teamspeak3.commands.parameter.Parameter.toString(Parameter.jav
a:35)                                                                                             
        at java.lang.String.valueOf(String.java:2994)                                             
        at java.lang.StringBuilder.append(StringBuilder.java:131)                                 
        at com.github.theholywaffle.teamspeak3.commands.Command.toString(Command.java:127)        
        at com.github.theholywaffle.teamspeak3.SocketWriter.run(SocketWriter.java:56)             
[2017-06-23 22:59:14.035] [SEVERE] Command clientupdate was not answered in time.                 
Exception in thread "main" java.lang.NullPointerException                                         
        at yt.TheOrder.DataController.DataController.init(DataController.java:55)                 
        at yt.TheOrder.DataController.Main.main(Main.java:7)`

I dont know what i am doing wrong. Or is this an apis bug?

**Comment by somefriggnidiot** [comment]
Please include the snippet of code causing this.

**Comment by rogermb** [comment]
Caused by user error (passing `null` to an API method); closed due to no further input from user.
