### ISSUE TITLE
Error while connecting query

### ISSUE THREAD

**Issue by InfectedCoding** [TheHolyWaffle/TeamSpeak-3-Java-API#223]
Hey,

when I try to execute: **ts3Query.connect();**, my application will stop.

I have made a debug:

`          System.out.println(1");
           ts3Query.connect();
           System.out.println("2");`

The console output is: 1
But I can't find the error in this code.

Please help me 👍

**Comment by rogermb** [comment]
... you need to give me a bit more information than that if you want me to be able to help you!

Can you please add your code and the full console output? What's more, how are you including this API to your project (jar file, maven, etc.)?

**Comment by InfectedCoding** [comment]
Hey,

sry. Here is my code: https://hastebin.com/fibadanopu.cs

The header of my file: 
    `private TS3Config ts3Config;`
    `private TS3Query ts3Query;`
    `private TS3Api ts3Api;`

Console ouput: 

`1`
`2`

**Comment by InfectedCoding** [comment]
I have this lib included by maven:

        `<dependency>`
            `<groupId>com.github.theholywaffle</groupId>`
            `<artifactId>teamspeak3-api</artifactId>`
            `<version>1.0.14</version>`
            `<scope>compile</scope>`
        `</dependency>`

**Comment by rogermb** [comment]
Well it's possible that `ts3Query.connect()` throws an exception (i.e. if there's no TS3 server at the given host and port), but in that case the exception should be logged in the console.

Are you maybe running that code in an `ExecutorService` or anything else off the main thread that might swallow those exceptions? Or are you only monitoring your Java application from a remote host that might not transmit messages that are logged to `System.err`?

**Comment by InfectedCoding** [comment]
Hey,

its a plugin for minecraft. And there are now errors or exceptions in the console.

**Comment by InfectedCoding** [comment]
And when I set a debug level, there will be a error while build maven artifact.

Error:

`[ERROR] symbol: method setDebugLevel(java.util.logging.Level)`

**Comment by rogermb** [comment]
Please try running that code outside your Minecraft plugin (i.e. create a new Java class with a `public static void main(String[] args)` and see if that works.

I'm almost certain that this is caused by the environment you're running your code in - either by just ignoring any thrown exceptions and not logging them properly or by somehow blocking access to IO methods that are required by the API.

**Comment by InfectedCoding** [comment]
With this "method" the console output:

1
2
Exception in thread "main" com.github.theholywaffle.teamspeak3.api.exception.TS3ConnectionFailedException: Could not connect to the TeamSpeak3 server
	at com.github.theholywaffle.teamspeak3.QueryIO.<init>(QueryIO.java:85)
	at com.github.theholywaffle.teamspeak3.TS3Query.connect(TS3Query.java:116)
	at de.infectedcoding.unknownlabs.api.core.TeamSpeakTest.main(TeamSpeakTest.java:28)
Caused by: java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at java.net.Socket.<init>(Socket.java:434)
	at java.net.Socket.<init>(Socket.java:211)
	at com.github.theholywaffle.teamspeak3.QueryIO.<init>(QueryIO.java:69)
	... 2 more

**Comment by rogermb** [comment]
Great!

This exception tells you that it could not connect to the TeamSpeak server. Are you *sure* that there is a TS3 server running on the same machine as you're running your code on? And are you sure that it's reachable?

If you're not sure, you can test that manually by starting `telnet` and entering the command `o 127.0.0.1 10011`. If you get back the message

```
TS3
Welcome to the TeamSpeak 3 ServerQuery interface, type "help" for a list of commands and "help <command>" for information on a specific command.
```

you know that the server is running, configured correctly and responding properly. If that command just hangs for 15 seconds, then you're not able to connect to the TS3 server.

**Comment by InfectedCoding** [comment]
Okay, thanks. Now the standalone application is running successfully. I will try to conntect both with a netty connection. Thanks <3

#Closed
