### ISSUE TITLE
UnsupportedOperationException: This code should have never made it into slf4j-api.jar

### ISSUE THREAD

**Issue by astrolamb-gaming** [TheHolyWaffle/TeamSpeak-3-Java-API#237]
I tried to test one of the examples, ClientInfoExample.java. I renamed it and ran it, but got the following error:
```
Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.slf4j.LoggerFactory.bind(LoggerFactory.java:150)
	at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:124)
	at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:412)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:357)
	at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:383)
	at com.github.theholywaffle.teamspeak3.TS3Query.<clinit>(TS3Query.java:44)
	at testts2.TestTS2.main(TestTS2.java:27)
Caused by: java.lang.UnsupportedOperationException: This code should have never made it into slf4j-api.jar
	at org.slf4j.impl.StaticLoggerBinder.<init>(StaticLoggerBinder.java:63)
	at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:44)
	... 7 more
C:\Users\Matthew\AppData\Local\NetBeans\Cache\8.2\executor-snippets\run.xml:53: Java returned: 1
BUILD FAILED (total time: 0 seconds)
```

Anyone know what might be causing this?

**Comment by Kakifrucht** [comment]
Are you on branch [1.1-dev](https://github.com/TheHolyWaffle/TeamSpeak-3-Java-API/tree/1.1-dev)?
The version used is 1.7.25. Maybe a conflict?

**Comment by astrolamb-gaming** [comment]
No, I'm using the master version. Should I be using 1.1-dev instead?

**Comment by Kakifrucht** [comment]
Well, 1.1-dev uses SLF4J. That would probably not be the fix to your issue though.

**Comment by rogermb** [comment]
@Kakifrucht 6e2c7374863770926b435b1fb9fd7f951662a0d6 is on master. He wouldn't be getting that exception if he weren't using it.

I think the much more likely cause of this issue is that the SLF4J logging provider is missing.
Most IDEs seem to be fetching all Maven dependencies, even those only activated conditionally. NetBeans doesn't seem to be doing this. But then again, this is not really NetBeans' fault.

It seems like we should be including the SLF4J-Simple dependency in both profiles, but with a different scope: `runtime` for when the "full" profile is not activated (meaning it is required for testing and running the application, i.e. the example classes, but not for compilation) and `compile` for when "full" is activated.

One more issue I'm encountering (but have chosen to ignore in the past) when running the provided tests is that the logging format when running the examples differs from when the `-with-dependencies` JAR is used. That's because the properties file in `src/main/resources/simplelogger.properties` is not where SLF4J-Simple expects it to be. Do you know if there is a way to point the provider to this file, @Kakifrucht?

@astrolamb-gaming Maybe running Maven once with the "full" profile activated (something along the lines of `maven -Pfull package`) might fix your issue.

**Comment by astrolamb-gaming** [comment]
@rogermb I'm not using Maven, and would prefer not to download another program. I'm going to try to reinstall SLF4J when I get back home, it's possible that I messed something up with that.

**Comment by Kakifrucht** [comment]
I guess the issue lies within the current Maven configuration then? 
I'm really bad at Maven though, so I can't really tell. The exclude is not overwritten?

https://github.com/TheHolyWaffle/TeamSpeak-3-Java-API/blob/master/pom.xml#L200

**Comment by rogermb** [comment]
@astrolamb-gaming Ah, I initially thought you were using Maven. You're likely just missing a logging provider, such as [slf4j-simple](https://mvnrepository.com/artifact/org.slf4j/slf4j-simple). Get whatever version matches slf4j's own version. You'll also need to have that JAR file available when running the examples, similar to slf4j itself. You can also use other logging providers, such as Logback, Log4j or the JUL wrapper implementation.

Moreover, if you decide to use slf4j-simple, you might want to add a configuration file to change the format of the log entries, since the default setting is rather verbose. You could, for example, use our default format located at [src/main/resources/simplelogger.properties](https://github.com/TheHolyWaffle/TeamSpeak-3-Java-API/blob/master/src/main/resources/simplelogger.properties)

I really don't want to pressure you into installing Maven, but I'd still like to add that all of this configuration usually wouldn't be necessary 😛

**Comment by astrolamb-gaming** [comment]
Ok, progress has been made: I got slf4j-simple and slf4j-api added and working (I think). I'm getting a different error instead, so I'm trying to track that down.  This is the error I'm getting:
```
Exception in thread "main" java.lang.NullPointerException
	at com.github.theholywaffle.teamspeak3.TS3Query.doCommand(TS3Query.java:186)
	at com.github.theholywaffle.teamspeak3.TS3Api.login(TS3Api.java:3299)
	at testts2.TestTS2.main(TestTS2.java:34)
```
This might be an issue with this project, or it could be me being an idiot (it has been a few months since I used Java extensively). 
What seems to be happening is that the login command is returning null. 
A bit of background: I'm trying to connect to a public server that doesn't require a password. I'm not an admin, is that a necessity for this to work? I could get access if needed.

**Comment by astrolamb-gaming** [comment]
Incidentally, the link to download the standalone Jar file is broken on the README.md.

**Comment by rogermb** [comment]
> A bit of background: I'm trying to connect to a public server that doesn't require a password. I'm not an admin, is that a necessity for this to work? I could get access if needed.

Regular clients and server query clients are not equal when it comes to permissions. While regular clients may not require a password, a logged in server query client requires a valid username and password. If you (as a regular client) have the required permissions on the server, you should able to generate such a server query login of your own. ([How to generate such a login](http://www.teamspeak3.com/support/teamspeak-3-add-server-query-user.php))

You may also connect as an anonymous server query client by just never calling `TS3Query#login`. However, you need to be aware that in that case, your permissions will be **very** limited.

Either way, do not call `TS3Query#login` with `null` as the arguments. That just causes exceptions further down the line 😄 

> EDIT 2: New issue. query.connect() is giving me issues:

This is either caused by your computer not being able to connect to the TS3 server or by setting the wrong IP and/or port in `TS3Config`.

Please note that regular TS3 clients and server query clients use different ports to connect to a TS3 server: regular clients use the voice port, which is 9987 by default, and which is specific to one *virtual* server. Server queries use the server query port, which is 10011 by default, and this port is shared by all virtual servers running on the same TS3 server.

After connecting to a TS3 server with a server query, use either [`TS3Api#selectVirtualServerByPort`](https://github.com/TheHolyWaffle/TeamSpeak-3-Java-API/blob/00b1e20cc8d4fc78562b0fd9f4a53dd320601289/src/main/java/com/github/theholywaffle/teamspeak3/TS3Api.java#L4047-L4063) or [`TS3Api#selectVirtualServerById`](https://github.com/TheHolyWaffle/TeamSpeak-3-Java-API/blob/00b1e20cc8d4fc78562b0fd9f4a53dd320601289/src/main/java/com/github/theholywaffle/teamspeak3/TS3Api.java#L4029-L4045) to select the correct virtual server.

> Incidentally, the link to download the standalone Jar file is broken on the README.md.

Curious! Seems like search.maven.org have changed how their links are structured. I'll update the link in the README file. Thanks for letting me know :smile:

**Comment by astrolamb-gaming** [comment]
Ok I think this covers most of my issues, although I currently don't have permissions to create a ServerQuery Login yet, but I can get that. Is there a better place to be bugging y'all with my questions? And should I close this, or do you want the reminder about the README and SLF4J?

**Comment by Kakifrucht** [comment]
The [Gitter](https://gitter.im/TheHolyWaffle/TeamSpeak-3-Java-API) is better suited for support.

**Comment by rogermb** [comment]
> And should I close this, or do you want the reminder about the README and SLF4J?

I think I'd prefer having this issue open as a reminder. I'll close it once I get the download link and the pom file fixed. Thanks for asking :blush:
