### ISSUE TITLE
Bug ERROR

### ISSUE THREAD

**Issue by ali120** [TheHolyWaffle/TeamSpeak-3-Java-API#246]
when i do Main.api.registerAllEvents();

i get this error
Exception in thread "main" java.lang.NullPointerException
	at com.github.theholywaffle.teamspeak3.TS3Query.doCommand(TS3Query.java:158)
	at com.github.theholywaffle.teamspeak3.TS3Api.registerEvent(TS3Api.java:3798)
	at com.github.theholywaffle.teamspeak3.TS3Api.registerEvent(TS3Api.java:3777)
	at com.github.theholywaffle.teamspeak3.TS3Api.registerAllEvents(TS3Api.java:3745)
	at net.craft.tsbot.events.Events.loadEvents(Events.java:26)
	at net.craft.tsbot.Main.main(Main.java:29)

and thanks for support .

**Comment by rogermb** [comment]
Could it be that you forgot to call TS3Api#connect()?

**Comment by ali120** [comment]
lock at Main class http://prntscr.com/hzhnk0

**Comment by somefriggnidiot** [comment]
Could you show us your Events class?

**Comment by ali120** [comment]
Events Class : http://prntscr.com/hzhtve

**Comment by rogermb** [comment]
You're defining local variables "config", "query", and "api", but you're also defining static fields "TS3Config", "query" and "api". These two are not the same!

**Comment by ali120** [comment]
can you give me the SCR ?

**Comment by rogermb** [comment]
```java
public static TS3Query query;
public static TS3Api api;

public static void main(String[] args) {
    TS3Config config = new TS3Config();
    config.setHost("localhost");
    config.setDebugLevel(Level.ALL);
    query = new TS3Query(config);
    query.connect();
    api = query.getApi();
    ... and so on ...
}
```

If this stuff isn't obvious to you, you'll need to familiarize yourself with Java.
