### ISSUE TITLE
Querry error?

### ISSUE THREAD

**Issue by MiamiRize** [TheHolyWaffle/TeamSpeak-3-Java-API#252]
```
com.github.theholywaffle.teamspeak3.api.exception.TS3ConnectionFailedException: An error occurred while sending a command to a teamspeak server at  #com.github.theholywaffle.teamspeak3.TS3Query.connect(TS3Query.java:96) ~[?:?] at de.mauricius17.teamspeak.verifier.system.TeamSpeakVerifier.onEnable(TeamSpeakVerifier.java:64) ~[?:?] at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot_1.8.8.jar:git-Spigot-db6de12-18fbb24] at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) 
[spigot_1.8.8.jar:git-Spigot-db6de12-18fbb24] at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) 
[spigot_1.8.8.jar:git-Spigot-db6de12-18fbb24] at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [spigot_1.8.8.jar:git-Spigot-db6de12-18fbb24] at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) 
[spigot_1.8.8.jar:git-Spigot-db6de12-18fbb24] at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [spigot_1.8.8.jar:git-Spigot-db6de12-18fbb24] at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) 
[spigot_1.8.8.jar:git-Spigot-db6de12-18fbb24] at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [spigot_1.8.8.jar:git-Spigot-db6de12-18fbb24] at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) 
[spigot_1.8.8.jar:git-Spigot-db6de12-18fbb24] at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [spigot_1.8.8.jar:git-Spigot-db6de12-18fbb24] at java.lang.Thread.run(Unknown Source) [?:1.8.0_161] Caused by: 
java.net.ConnectException: Connection refused: connect at 
java.net.DualStackPlainSocketImpl.connect0(Native Method) ~[?:1.8.0_161] at 
java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source) ~[?:1.8.0_161] at 
java.net.AbstractPlainSocketImpl.doConnect(Unknown Source) ~[?:1.8.0_161] at 
java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source) ~[?:1.8.0_161] at 
java.net.AbstractPlainSocketImpl.connect(Unknown Source) ~[?:1.8.0_161] at 
java.net.PlainSocketImpl.connect(Unknown Source) ~[?:1.8.0_161] at 
java.net.SocksSocketImpl.connect(Unknown Source) ~[?:1.8.0_161] at java.net.Socket.connect(Unknown Source) ~[?:1.8.0_161] at java.net.Socket.connect(Unknown Source) ~[?:1.8.0_161] at java.net.Socket.<init>(Unknown Source) ~[?:1.8.0_161] at java.net.Socket.<init>(Unknown Source) ~[?:1.8.0_161] at com.github.theholywaffle.teamspeak3.TS3Query.connect(TS3Query.java:84) ~[?:?]
```

e: Code tags.

**Comment by rogermb** [comment]
The server refused the connection, as you can see in the stack trace.
That means that you probably either used the wrong IP address or query port.

Make sure these two are set correctly in `TS3Config`. Also make sure that you understand the [difference](https://github.com/TheHolyWaffle/TeamSpeak-3-Java-API/wiki/FAQ#what-is-the-difference-between-a-voice-and-a-query-port) between the voice port (the port you use when connecting to the server with a regular TS3 client) and the query port (the port you use to connect with a server query).
