### ISSUE TITLE
teamspeak3-api-1.1.0-with-dependencies; Cant Start Bot

### ISSUE THREAD

**Issue by RemadyReturns** [TheHolyWaffle/TeamSpeak-3-Java-API#268]
Hi, I just got this bug. I don't know how to fix. Can someone help?

Exception in thread "main" com.github.theholywaffle.teamspeak3.api.exception.TS3ConnectionFailedException: Could not connect to the TeamSpeak3 server
        at com.github.theholywaffle.teamspeak3.QueryIO.<init>(QueryIO.java:82)
        at com.github.theholywaffle.teamspeak3.TS3Query.connect(TS3Query.java:128)
        at de.remadyreturns.team.Bot.main(Bot.java:66)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at java.net.Socket.connect(Socket.java:538)
        at java.net.Socket.<init>(Socket.java:434)
        at java.net.Socket.<init>(Socket.java:211)
        at com.github.theholywaffle.teamspeak3.QueryIO.<init>(QueryIO.java:65)
         . . .   2 more

I just wrote this in line 66 
66 » query.connect();
does anyone know how to fix? :)

Thanks;

**Comment by Jhidzzo** [comment]
I have the same problem...

**Comment by rogermb** [comment]
Make sure that you've set the correct IP / host name using `TS3Query#setHost` and the correct server query port using `TS3Query#setQueryPort` before passing that TS3Query object to TS3Query's constructor. Please also make sure that you understand the [difference between the voice and the query port](https://github.com/TheHolyWaffle/TeamSpeak-3-Java-API/wiki/FAQ#what-is-the-difference-between-a-voice-and-a-query-port).

It may a be a good idea to check out some of the example classes in the "examples" directory.
