### ISSUE TITLE
TS3CommandFailedException on leave

### ISSUE THREAD

**Issue by Bry4nWayne** [TheHolyWaffle/TeamSpeak-3-Java-API#311]
Everytime someone is leaving my server, I'm getting this exception, only on the leave event.

`[pool-1-thread-13] ERROR com.github.theholywaffle.teamspeak3.EventManager - Event listener threw an exception
com.github.theholywaffle.teamspeak3.api.exception.TS3CommandFailedException: A "clientinfo" command returned with a server error.
 invalid clientID (ID 512)
        at com.github.theholywaffle.teamspeak3.api.CommandFuture.checkForFailure(CommandFuture.java:415)
        at com.github.theholywaffle.teamspeak3.api.CommandFuture.getUninterruptibly(CommandFuture.java:356)
        at com.github.theholywaffle.teamspeak3.TS3Api.getClientInfo(TS3Api.java:1945)
        at Events.onClientLeave(Events.java:30)
        at com.github.theholywaffle.teamspeak3.api.event.ClientLeaveEvent.fire(ClientLeaveEvent.java:51)
        at com.github.theholywaffle.teamspeak3.EventManager$ListenerTask.run(EventManager.java:169)
        at com.github.theholywaffle.teamspeak3.TS3Query.lambda$submitUserTask$0(TS3Query.java:232)
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)`

the method where I'm getting the exception is

`    @Override
    public void onClientLeave(ClientLeaveEvent e) {
        ClientInfo client = api.getClientInfo(e.getClientId());
        ConsoleOut.print("ClientLeave " + client.getNickname());
    }`

Every other event looks like this and there are no issues.

**Comment by rogermb** [comment]
Basically, `getClientInfo` only works for clients who are online. By the time your query gets the `clientleftview` notification, the client has already left the server, so you can't get use `getClientInfo` anymore.

If you still need some information about the client in your `onClientLeave` handler, you'll have to store it somewhere earlier, e.g. by using a HashMap that maps a client ID (int) to a client object (Client or ClientInfo).

See also [the FAQ](https://github.com/TheHolyWaffle/TeamSpeak-3-Java-API/wiki/FAQ#why-am-i-getting-a-command-error-by-calling-getclientinfo-on-a-clientleaveevent) 😄
