### ISSUE TITLE
Everytime if I import the src into my src

### ISSUE THREAD

**Issue by NetzkroneHD** [TheHolyWaffle/TeamSpeak-3-Java-API#326]
I already added the slf4j-api-1.7.26 src also

java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory
    at com.github.theholywaffle.teamspeak3.TS3Query.<clinit>(TS3Query.java:18)
    at de.NetzkroneHD.Proxy.Main.<clinit>(Main.java:147)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
    at java.lang.reflect.Constructor.newInstance(Unknown Source)
    at net.md_5.bungee.api.plugin.PluginManager.enablePlugin(PluginManager.java:325)
    at net.md_5.bungee.api.plugin.PluginManager.loadPlugins(PluginManager.java:232)
    at net.md_5.bungee.BungeeCord.start(BungeeCord.java:266)
    at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:62)
    at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory
    at net.md_5.bungee.api.plugin.PluginClassloader.loadClass0(PluginClassloader.java:53)
    at net.md_5.bungee.api.plugin.PluginClassloader.loadClass(PluginClassloader.java:27)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 11 more

Main 147 = public static TS3Query query = new TS3Query(config);

**Comment by FLOODY88** [comment]
Hi @NetzkroneHD, please make sure that you downloaded the [latest release with dependencies](https://search.maven.org/remote_content?g=com.github.theholywaffle&a=teamspeak3-api&v=LATEST&c=with-dependencies) and added it to the build path of your project. When you're using Maven, please follow [Option 2](https://search.maven.org/remote_content?g=com.github.theholywaffle&a=teamspeak3-api&v=LATEST&c=with-dependencies).

It would be nice if you could provide some more information, e.g:
- When does the problem occur?
    (if possible, provide a minimal, complete, and verifiable example of your code - not just one line)
- What did you try to solve the problem?

However, it seems there is something wrong with your build path. A `NoClassDefFoundError` occurs when there is a class file, your code depends on, that is present at compile time but not found at runtime.
