### ISSUE TITLE
Connect to Server Issue

### ISSUE THREAD

**Issue by PrinzKenny1** [TheHolyWaffle/TeamSpeak-3-Java-API#327]
Hey, I just cloned your repo and compiled myself a .jar but whenever I try to connect to a server, I got this error.

com.github.theholywaffle.teamspeak3.api.exception.TS3ConnectionFailedException: ConnectionHandler threw exception in connect handler
        at com.github.theholywaffle.teamspeak3.TS3Query.doConnect(TS3Query.java:176)
        at com.github.theholywaffle.teamspeak3.TS3Query.connect(TS3Query.java:149)
        at de.prinzkenny1.querybot.objects.TeamspeakInstance.<init>(TeamspeakInstance.java:100)
        at de.prinzkenny1.querybot.QueryBot.createBot(QueryBot.java:224)
        at de.prinzkenny1.querybot.QueryBot.lambda$main$5(QueryBot.java:115)
        at spark.RouteImpl$1.handle(RouteImpl.java:72)
        at spark.http.matching.Routes.execute(Routes.java:61)
        at spark.http.matching.MatcherFilter.doFilter(MatcherFilter.java:134)
        at spark.embeddedserver.jetty.JettyHandler.doHandle(JettyHandler.java:50)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1671)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
        at org.eclipse.jetty.server.Server.handle(Server.java:505)
        at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:370)
        at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:267)
        at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
        at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
        at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:698)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:804)
        at java.base/java.lang.Thread.run(Thread.java:835)

**Comment by rogermb** [comment]
That just sounds like a generic connection issue.

Make sure that your hostname / IP and your query port are correct. Port numbers are **not** part of the hostanme / IP. Make sure that you can actually communicate with your server using that IP and port. Understand the difference between TS3's voice ports and the query port. Check that your TS3 server actually enabled the use of the serverquery.

**Comment by PrinzKenny1** [comment]
I actually worked already with the API a long time ago. With Version 1.2 everything is working like a charm but with 1.3 unfortunately it doesn't work anymore
