### ISSUE TITLE
[DEBUG] Random Socket Read Time Out

### ISSUE THREAD

**Issue by P-Kito** [TheHolyWaffle/TeamSpeak-3-Java-API#328]
After a long uptime of my bot I get a random:

```2019-05-10 04:48:16.735 [DEBUG] [clientlist] > clientlist -uid -away -voice -times -groups -info -icon -country -ip -badges
2019-05-10 04:48:16.735 [DEBUG] [clientlist] < clid=3 cid=1934 client_database_id=25384 client_nickname=Sleisend\/Felix client_type=0 client_away=0 client_away_message client_flag_talking=0 client_input_muted=0 client_output_muted=1 client_input_hardware=1 client_output_hardware=1 client_talk_power=75 client_is_talker=0 client_is_priority_speaker=0 client_is_recording=0 client_is_channel_commander=0 client_unique_identifier=R8mWE1AdU0J6GnaaTMSxZypW3Xw= client_servergroups=9,336,346,425 client_channel_group_id=8 client_channel_group_inherited_channel_id=1934 client_version=3.2.5\s[Build:\s1555517253] client_platform=Windows client_idle_time=30205006 client_created=1477263773 client_lastconnected=1557404184 client_icon_id=0 client_country=DE connection_client_ip=84.181.181.121 client_badges=overwolf=0:badges=64221fd1-706c-4bb2-ba55-996c39effa79,f22c22f1-8e2d-4d99-8de9-f352dc26ac5b,b9c7d6ad-5b99-40fb-988c-1d02ab6cc130|clid=12 cid=1934 client_database_id=29410 client_nickname=Hendrik client_type=0 client_away=0 client_away_message client_flag_talking=0 client_input_muted=0 client_output_muted=1 client_input_hardware=1 client_output_hardware=1 client_talk_power=50 client_is_talker=0 client_is_priority_speaker=0 client_is_recording=0 client_is_channel_commander=0 client_unique_identifier=orFAWnr\/yPjEsefbsAdLV2jhw6g= client_servergroups=336,346,375 client_channel_group_id=8 client_channel_group_inherited_channel_id=1934 client_version=3.2.5\s[Build:\s1555517253] client_platform=Windows client_idle_time=124653547 client_created=1517658721 client_lastconnected=1557331361 client_icon_id=0 client_country=DE connection_client_ip=217.95.147.20 client_badges=overwolf=0:badges=534c9582-ab02-4267-aec6-2d94361daa2a,4eef1ecf-a0ea-423d-bfd0-496543a00305,b9c7d6ad-5b99-40fb-988c-1d02ab6cc130|clid=14 cid=1934 client_database_id=29232 client_nickname=Blazing\s\/\sRobin client_type=0 client_away=0 client_away_message client_flag_talking=0 client_input_muted=1 client_output_muted=1 client_input_hardware=0 client_output_hardware=1 client_talk_power=100 client_is_talker=0 client_is_priority_speaker=0 client_is_recording=0 client_is_channel_commander=0 client_unique_identifier=K6qAFRqVKY1RZGc9IXSb9RW\/TbU= client_servergroups=6,335,338,346,360 client_channel_group_id=8 client_channel_group_inherited_channel_id=1934 client_version=3.2.5\s[Build:\s1555517253] client_platform=Windows client_idle_time=33583967 client_created=1514972026 client_lastconnected=1557422901 client_icon_id=0 client_country=DE connection_client_ip=91.248.229.77 client_badges=overwolf=0:badges=4eef1ecf-a0ea-423d-bfd0-496543a00305,534c9582-ab02-4267-aec6-2d94361daa2a,b9c7d6ad-5b99-40fb-988c-1d02ab6cc130|clid=20 cid=12860 client_database_id=27801 client_nickname=Ching\sChong\sBoi client_type=0 client_away=0 client_away_message client_flag_talking=0 client_input_muted=0 client_output_muted=0 client_input_hardware=1 client_output_hardware=1 client_talk_power=50 client_is_talker=0 client_is_priority_speaker=0 client_is_recording=0 client_is_channel_commander=0 client_unique_identifier=jOIaCGOLE\/BjB5Kq0I5RSloahyk= client_servergroups=7,346,455 client_channel_group_id=6 client_channel_group_inherited_channel_id=12860 client_version=3.2.5\s[Build:\s1555517253] client_platform=Windows client_idle_time=22877 client_created=1498822251 client_lastconnected=1557389134 client_icon_id=0 client_country=FR connection_client_ip=86.208.127.150 client_badges=overwolf=0|clid=25 cid=18916 client_database_id=30226 client_nickname=[Use\sme!]\sFree\sMusicBot client_type=0 client_away=0 client_away_message client_flag_talking=0 client_input_muted=0 client_output_muted=0 client_input_hardware=1 client_output_hardware=1 client_talk_power=75 client_is_talker=0 client_is_priority_speaker=0 client_is_recording=0 client_is_channel_commander=0 client_unique_identifier=RnXBeuRPuRru\/J29n9mRsnl5jFg= client_servergroups=333,477 client_channel_group_id=6 client_channel_group_inherited_channel_id=18916 client_version=3.2.5\s[Build:\s1555517253] client_platform=Linux client_idle_time=17071498 client_created=1530409850 client_lastconnected=1556324767 client_icon_id=0 client_country connection_client_ip=127.0.0.1 client_badges|clid=27 cid=18916 client_database_id=30220 client_nickname=[Use\sme!]\sFree\sMusicBot1 client_type=0 client_away=0 client_away_message client_flag_talking=0 client_input_muted=0 client_output_muted=0 client_input_hardware=1 client_output_hardware=1 client_talk_power=75 client_is_talker=0 client_is_priority_speaker=0 client_is_recording=0 client_is_channel_commander=0 client_unique_identifier=WdCTV6\/5pZeUtyl9D1nxvK71xP0= client_servergroups=333,477 client_channel_group_id=6 client_channel_group_inherited_channel_id=18916 client_version=3.2.5\s[Build:\s1555517253] client_platform=Linux client_idle_time=17082324 client_created=1530311822 client_lastconnected=1556324767 client_icon_id=0 client_country connection_client_ip=127.0.0.1 client_badges|clid=28 cid=18916 client_database_id=30225 client_nickname=[Use\sme!]\sFree\sMusicBot2 client_type=0 client_away=0 client_away_message client_flag_talking=0 client_input_muted=0 client_output_muted=0 client_input_hardware=1 client_output_hardware=1 client_talk_power=75 client_is_talker=0 client_is_priority_speaker=0 client_is_recording=0 client_is_channel_commander=0 client_unique_identifier=e2Le0hAiW0Kbeltsq1zSVDMj9w0= client_servergroups=333,477 client_channel_group_id=6 client_channel_group_inherited_channel_id=18916 client_version=3.2.5\s[Build:\s1555517253] client_platform=Linux client_idle_time=17076673 client_created=1530409850 client_lastconnected=1556324767 client_icon_id=0 client_country connection_client_ip=127.0.0.1 client_badges|clid=64 cid=168 client_database_id=120 client_nickname=K-Teamspeak\sRanking\sBot client_type=1 client_away=0 client_away_message client_flag_talking=0 client_input_muted=0 client_output_muted=0 client_input_hardware=0 client_output_hardware=0 client_talk_power=75 client_is_talker=0 client_is_priority_speaker=0 client_is_recording=0 client_is_channel_commander=0 client_unique_identifier=BBEcafpRfoyLFJ9KT2P05ARGH8o= client_servergroups=2,7,333 client_channel_group_id=8 client_channel_group_inherited_channel_id=168 client_version=ServerQuery client_platform=ServerQuery client_idle_time=11823053 client_created=1348254188 client_lastconnected=1518994691 client_icon_id=0 client_country=DE connection_client_ip=37.120.188.152 client_badges|clid=66 cid=13432 client_database_id=29544 client_nickname=David client_type=0 client_away=0 client_away_message client_flag_talking=0 client_input_muted=0 client_output_muted=1 client_input_hardware=1 client_output_hardware=1 client_talk_power=50 client_is_talker=0 client_is_priority_speaker=0 client_is_recording=0 client_is_channel_commander=0 client_unique_identifier=+8rt\/oZA6wMJ9J6bL59vap8E1us= client_servergroups=336,392 client_channel_group_id=8 client_channel_group_inherited_channel_id=13432 client_version=3.2.5\s[Build:\s1555517253] client_platform=Windows client_idle_time=9133835 client_created=1519433627 client_lastconnected=1557420638 client_icon_id=0 client_country=PT connection_client_ip=79.169.236.163 client_badges=Overwolf=0
2019-05-10 04:48:16.735 [DEBUG] [clientlist] < error id=0 msg=ok
2019-05-10 04:49:16.735 [DEBUG] [whoami] > whoami
2019-05-10 04:49:16.774 [ERROR] Connection timed out.
java.net.SocketTimeoutException: Read timed out
	at java.base/java.net.SocketInputStream.socketRead0(Native Method)
	at java.base/java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.base/sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
	at java.base/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
	at java.base/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	at java.base/java.io.InputStreamReader.read(InputStreamReader.java:185)
	at java.base/java.io.BufferedReader.fill(BufferedReader.java:161)
	at java.base/java.io.BufferedReader.readLine(BufferedReader.java:326)
	at java.base/java.io.BufferedReader.readLine(BufferedReader.java:392)
	at com.github.theholywaffle.teamspeak3.SocketReader.run(SocketReader.java:82)
2019-05-10 04:49:16.826 [ERROR] [Connection] Disconnected from TS3 server
```

Any ideas?

**Comment by P-Kito** [comment]
Using: 
teamspeak3-api-1.1.0-with-dependencies.jar

**Comment by TheHolyWaffle** [comment]
This is most likely a generic connection issue between you and the server.
You should write your application to be able to handle such network issues.

Op za 11 mei 2019 om 23:44 schreef P-Kito <notifications@github.com>:

**Comment by P-Kito** [comment]
Hmm. Maybe. I will monitor it.
