### ISSUE TITLE
Timeout 

### ISSUE THREAD

**Issue by DevJoey** [TheHolyWaffle/TeamSpeak-3-Java-API#330]
I have this Error

2019-05-26 20:46:06.007 [ERROR] Connection timed out.
java.net.SocketTimeoutException: Read timed out
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.socketRead(Unknown Source)
        at java.net.SocketInputStream.read(Unknown Source)
        at java.net.SocketInputStream.read(Unknown Source)
        at sun.nio.cs.StreamDecoder.readBytes(Unknown Source)
        at sun.nio.cs.StreamDecoder.implRead(Unknown Source)
        at sun.nio.cs.StreamDecoder.read(Unknown Source)
        at java.io.InputStreamReader.read(Unknown Source)
        at java.io.BufferedReader.fill(Unknown Source)
        at java.io.BufferedReader.readLine(Unknown Source)
        at java.io.BufferedReader.readLine(Unknown Source)
        at com.github.theholywaffle.teamspeak3.SocketReader.run(SocketReader.java:83)
2019-05-26 20:46:06.026 [ERROR] [Connection] Disconnected from TS3 server

Have someone a fix for that Problem. API unuseble

**Comment by Jopeeee** [comment]
I've the same Problem, seems to be a Bug. Please Help!

**Comment by LinuxClient** [comment]
The TeamSpeak-3-Java-API doesn't work with TeamSpeak-Version: 3.8.0

**Comment by florian262000** [comment]
Is it already known when versions 3.8.0 and 3.9.0 will be supported?

**Comment by rogermb** [comment]
Sorry for taking so long to respond. Had a lot of IRL stuff going on, and it'll probably be another 3-4 weeks until I'll be able to work on this API again.

@DevJoey & @Jopeeee  When are you getting that exception?
Does it always occur when you're first connecting to the server, or does it happen at random times?

If this exception occurs when you're connecting for the first time, you've almost certainly either set the wrong IP or the wrong port. Make sure that you're using the **query** port and not the "normal" voice port when connecting to your TS3 server.

@LinuxClient Can you be a bit more specific about what doesn't work?

@florian262000 The API still works with v3.8.0 and newer, but the new TS3 server features are not supported yet. I should be able to work on this in ~1 month 😄
