### ISSUE TITLE
Time out

### ISSUE THREAD

**Issue by MpChriss** [TheHolyWaffle/TeamSpeak-3-Java-API#349]
My Teamspeak bot have every time a Time out idk why.

No difference between Sync and Async Api!
Code: 
  
```
public Teamspeak(RayBackEnd instance) {
      (new Thread(() -> {
                TS3Config config = new TS3Config();
                this.query = new TS3Query(config);
                this.api = this.query.getApi();

                config.setHost("***");
                config.setReconnectStrategy(ReconnectStrategy.linearBackoff());
                config.setFloodRate(TS3Query.FloodRate.UNLIMITED);
                config.setEnableCommunicationsLogging(true);
                this.query.connect();
                this.api.login("***", "***");
                this.api.selectVirtualServerById(1);
                try {
                    this.api.setNickname("VerifyClient");
                } catch (Exception e) {
                    this.api.setNickname("VerifyClient (" + RandomStringUtils.randomAlphanumeric(4) + ")");
                } /**This is because he called the name VerifyClient is allready in use!*/
                assert this.api != null;
                new TeamspeakEvents(instance);
                new TeamspeakAFKTimer(instance);
                RayBase.getLogger().sendLog(RayLogger.log.GOOD, "Teamspeak Bot wurde gestartet.");
            })).start();
}
```
   
TeamspeakAKFTimer claas;
   ```
public static List<Integer> onlinesups = new ArrayList<>();
    public static Map<Integer, Integer> afk = new HashMap<>();
    public static ScheduledTask afkTimer;

    public TeamspeakAFKTimer(RayBackEnd instance) {
        final TS3Api apiAsync = instance.getTeamspeak().getApi();
        afkTimer = BungeeCord.getInstance().getScheduler().schedule(RayBackEnd.getInstance(), new Runnable() {
            int i = 0;

            @Override
            public void run() {
                if (!instance.getTeamspeak().getQuery().isConnected()) return;
                    checkSupportChannel(apiAsync, instance);
            }
        }, 1, 1, TimeUnit.MINUTES);
    }

    private static void checkSupportChannel(TS3Api apiAsync, RayBackEnd instance) {
        if (apiAsync.getChannelInfo(87) == null) {
            RayBase.getLogger().sendLog(RayLogger.log.HARD, "Teamspeak Channel cannot Found.");
            return;
        }
        try {
            onlinesups.clear();
            for (Client client : apiAsync.getClients()) {
                if (client.isInServerGroup(instance.getTeamspeak().getSupportGroup()))
                    if (client.getChannelId() != 61 && client.getChannelId() != 56)
                        onlinesups.add(client.getId());
            }
            Calendar c = Calendar.getInstance();
            c.setTimeZone(TimeZone.getTimeZone("Europe/Berlin"));
            Map<ChannelProperty, String> property = new HashMap<ChannelProperty, String>();
            ChannelInfo result = apiAsync.getChannelInfo(87);
                if (onlinesups.size() == 0 | ((c.get(Calendar.HOUR_OF_DAY) >= 20 && c.get(Calendar.MINUTE) == 0) && (c.get(Calendar.HOUR_OF_DAY) <= 13 && c.get(Calendar.MINUTE) == 0))) {
                    if (!result.getName().contains("•〢Support × Wartezone [CLOSED]")) {
                        property.put(ChannelProperty.CHANNEL_NAME, "•〢Support × Wartezone [CLOSED]");
                        property.put(ChannelProperty.CHANNEL_MAXCLIENTS, "0");
                        property.put(ChannelProperty.CHANNEL_FLAG_MAXCLIENTS_UNLIMITED, "0");
                        apiAsync.editChannel(87, property);
                        property.clear();
                    }
                } else if (!result.getName().contains("•〢Support × Wartezone [OPEN]")) {
                    property.put(ChannelProperty.CHANNEL_NAME, "•〢Support × Wartezone [OPEN]");
                    property.put(ChannelProperty.CHANNEL_MAXCLIENTS, "1");
                    property.put(ChannelProperty.CHANNEL_FLAG_MAXCLIENTS_UNLIMITED, "1");
                    apiAsync.editChannel(87, property);
                    property.clear();
                }
        } catch (Exception e) {
            RayBase.getLogger().sendLog(RayLogger.log.HARD, "Teamspeak Channel checker: " + e.getMessage());
        }
    }
```

My BungeeCord Log:
```
[20:53:51] [[TeamSpeak-3-Java-API] SocketReader/ERROR] [com.github.theholywaffle.teamspeak3.SocketReader]: Connection timed out.
java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method) ~[?:1.8.0_232]
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116) ~[?:1.8.0_232]
	at java.net.SocketInputStream.read(SocketInputStream.java:171) ~[?:1.8.0_232]
	at java.net.SocketInputStream.read(SocketInputStream.java:141) ~[?:1.8.0_232]
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284) ~[?:1.8.0_232]
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326) ~[?:1.8.0_232]
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178) ~[?:1.8.0_232]
	at java.io.InputStreamReader.read(InputStreamReader.java:184) ~[?:1.8.0_232]
	at java.io.BufferedReader.fill(BufferedReader.java:161) ~[?:1.8.0_232]
	at java.io.BufferedReader.readLine(BufferedReader.java:324) ~[?:1.8.0_232]
	at java.io.BufferedReader.readLine(BufferedReader.java:389) ~[?:1.8.0_232]
	at com.github.theholywaffle.teamspeak3.SocketReader.run(SocketReader.java:83) ~[?:?]
[20:53:51] [pool-4-thread-1/ERROR] [com.github.theholywaffle.teamspeak3.api.reconnect.DisconnectingConnectionHandler]: [Connection] Disconnected from TS3 server
[20:53:51] [RayEnd Pool Thread #2/ERROR]: Task BungeeTask(sched=net.md_5.bungee.scheduler.BungeeScheduler@74cadd41, id=2, owner=de.chris.RayBackEnd@7bc10d84, task=de.chris.managers.teamspeak.TeamspeakAFKTimer$1@29545afe, delay=60000, period=60000, running=true) encountered an exception
com.github.theholywaffle.teamspeak3.api.exception.TS3QueryShutDownException: The query was shut down or disconnected.
	at com.github.theholywaffle.teamspeak3.api.CommandFuture.checkForFailure(CommandFuture.java:415) ~[?:?]
	at com.github.theholywaffle.teamspeak3.api.CommandFuture.getUninterruptibly(CommandFuture.java:356) ~[?:?]
	at com.github.theholywaffle.teamspeak3.TS3Api.getChannelInfo(TS3Api.java:1839) ~[?:?]
	at de.chris.managers.teamspeak.TeamspeakAFKTimer.checkSupportChannel(TeamspeakAFKTimer.java:81) ~[?:?]
	at de.chris.managers.teamspeak.TeamspeakAFKTimer.access$000(TeamspeakAFKTimer.java:24) ~[?:?]
	at de.chris.managers.teamspeak.TeamspeakAFKTimer$1.run(TeamspeakAFKTimer.java:37) ~[?:?]
	at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63) ~[bungee.jar:git:Travertine-Bootstrap:1.15-SNAPSHOT:e40d7ce:125]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_232]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_232]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]


```

**Comment by MpChriss** [comment]
I Know now that my Teamspeak Server Version to New is, but witch Version i have to use without Any Errors and bugs? with the api? Thank you.

**Comment by GeRaged** [comment]
Have u fixed this error?

The query was shut down or disconnected.

**Comment by rogermb** [comment]
Hi @MpChriss. Sorry for taking so long to respond.

It looks like you are able to connect to the server, but you're getting disconnected shortly after.
Almost always, this is the case because people forget to whitelist the IP of their query client on the TS3 server while using the `UNLIMITED` flood rate. To help diagnose this issue, you could try running the query with the default flood rate. If you don't get disconnected, not properly being whitelisted is what caused your issue.

Also, note that the whitelist file is only being read once when the TS3 server is started, so you have to restart the server for any changes to take effect.
