### ISSUE TITLE
my bot does not start anymore i have an erro

### ISSUE THREAD

**Issue by LuisKanze** [TheHolyWaffle/TeamSpeak-3-Java-API#386]
The Bot has startet
[2020-12-20 20:45:43.094] [SEVERE] TS3 command error: {msg=server is not running, id=1033}
[2020-12-20 20:45:43.445] [SEVERE] TS3 command error: {msg=invalid serverID, id=1024}
[2020-12-20 20:45:43.796] [SEVERE] TS3 command error: {msg=invalid serverID, id=1024}
[2020-12-20 20:45:44.147] [SEVERE] TS3 command error: {msg=invalid serverID, id=1024}
[2020-12-20 20:45:44.500] [SEVERE] TS3 command error: {msg=invalid serverID, id=1024}
[2020-12-20 20:45:44.870] [SEVERE] TS3 command error: {msg=invalid serverID, id=1024}
[2020-12-20 20:45:45.199] [SEVERE] TS3 command error: {msg=invalid serverID, id=1024}
[2020-12-20 20:45:45.550] [SEVERE] TS3 command error: {msg=invalid serverID, id=1024}
[2020-12-20 20:45:45.902] [SEVERE] TS3 command error: {msg=invalid serverID, id=1024}
Exception in thread "Timer-0" java.lang.NullPointerException
	at de.luis.teamspeakbot.events.AFKMover$1.run(AFKMover.java:30)
	at java.util.TimerThread.mainLoop(Timer.java:555)
	at java.util.TimerThread.run(Timer.java:505)
[2020-12-20 20:46:45.905] [SEVERE] TS3 command error: {msg=invalid serverID, id=1024}
[2020-12-20 20:46:45.906] [WARNING] KeepAlive thread has stopped!
com.github.theholywaffle.teamspeak3.api.exception.TS3Exception: Unhandled exception
	at com.github.theholywaffle.teamspeak3.api.CommandFuture.checkForFailure(CommandFuture.java:389)
	at com.github.theholywaffle.teamspeak3.api.CommandFuture.get(CommandFuture.java:271)
	at com.github.theholywaffle.teamspeak3.KeepAliveThread.run(KeepAliveThread.java:51)
Caused by: com.github.theholywaffle.teamspeak3.api.exception.TS3CommandFailedException: A command returned with a server error.
invalid serverID (ID 1024)
	at com.github.theholywaffle.teamspeak3.TS3ApiAsync.hasFailed(TS3ApiAsync.java:5144)
	at com.github.theholywaffle.teamspeak3.TS3ApiAsync.access$000(TS3ApiAsync.java:79)
	at com.github.theholywaffle.teamspeak3.TS3ApiAsync$59.handle(TS3ApiAsync.java:5072)
	at com.github.theholywaffle.teamspeak3.SocketReader$2.run(SocketReader.java:129)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

This is the Erro

**Comment by Voyaris** [comment]
Did you even look at the stack trace?
I looked at it for 5 seconds and immediately discovered your error.
![image](https://user-images.githubusercontent.com/25487038/105095665-45612f00-5aa6-11eb-8550-e71f16d8fadf.png)
You use a wrong serverID as explained in the stack trace
