### ISSUE TITLE
Icon upload failed (Connection refused)

### ISSUE THREAD

**Issue by Angxstupst** [TheHolyWaffle/TeamSpeak-3-Java-API#396]
Hey, I'm trying to upload an icon. But errors comes

```
private static void setClientIcon(String uniqueId, String head) {
        try {
            long v = 0;
            URL url = new URL("https://minotar.net/helm/" + head + "/16.png");
            ByteArrayOutputStream outputStream = new ByteArrayOutputStream();
            try (InputStream inputStream = url.openStream()) {
                int n = 0;
                byte[] buffer = new byte[1024];
                while(-1 != (n = inputStream.read(buffer))) {
                    outputStream.write(buffer, 0, n);
                }
            }
            v = Main.api.uploadIconDirect(outputStream.toByteArray());
            Main.api.addClientPermission(Main.api.getClientByUId(uniqueId).getDatabaseId(), "i_icon_id", (int) v, true);
        }catch(Exception exception) {
            exception.printStackTrace();
        }
    }
```

```
[pool-5-thread-3] INFO com.github.theholywaffle.teamspeak3.FileTransferHelper - [Upload 2] Upload started
[Lobby-1][07:50:07 WARN]: [pool-5-thread-3] WARN com.github.theholywaffle.teamspeak3.FileTransferHelper - [Upload 2] Upload failed: Connection refused (Connection refused)
[Lobby-1][07:50:07 WARN]: com.github.theholywaffle.teamspeak3.api.exception.TS3FileTransferFailedException: Upload failed
[Lobby-1][07:50:07 WARN]:       at com.github.theholywaffle.teamspeak3.api.CommandFuture.checkForFailure(CommandFuture.java:415)
[Lobby-1][07:50:07 WARN]:       at com.github.theholywaffle.teamspeak3.api.CommandFuture.getUninterruptibly(CommandFuture.java:356)
[Lobby-1][07:50:07 WARN]:       at com.github.theholywaffle.teamspeak3.TS3Api.uploadIconDirect(TS3Api.java:4528)
[Lobby-1][07:50:07 WARN]:       at net.universalcw.ts.main.events.EventManager.setClientIcon(EventManager.java:184)
[Lobby-1][07:50:07 WARN]:       at net.universalcw.ts.main.events.EventManager.access$000(EventManager.java:27)
[Lobby-1][07:50:07 WARN]:       at net.universalcw.ts.main.events.EventManager$1.onTextMessage(EventManager.java:80)
[Lobby-1][07:50:07 WARN]:       at com.github.theholywaffle.teamspeak3.api.event.TextMessageEvent.fire(TextMessageEvent.java:69)
[Lobby-1][07:50:07 WARN]:       at com.github.theholywaffle.teamspeak3.EventManager$ListenerTask.run(EventManager.java:169)
[Lobby-1][07:50:07 WARN]:       at com.github.theholywaffle.teamspeak3.TS3Query.lambda$submitUserTask$0(TS3Query.java:232)
[Lobby-1][07:50:07 WARN]:       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[Lobby-1][07:50:07 WARN]:       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[Lobby-1][07:50:07 WARN]:       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[Lobby-1][07:50:07 WARN]:       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[Lobby-1][07:50:07 WARN]:       at java.lang.Thread.run(Thread.java:748)
[Lobby-1][07:50:07 WARN]: Caused by: java.net.ConnectException: Connection refused (Connection refused)
[Lobby-1][07:50:07 WARN]:       at java.net.PlainSocketImpl.socketConnect(Native Method)
[Lobby-1][07:50:07 WARN]:       at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
[Lobby-1][07:50:07 WARN]:       at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
[Lobby-1][07:50:07 WARN]:       at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
[Lobby-1][07:50:07 WARN]:       at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
[Lobby-1][07:50:07 WARN]:       at java.net.Socket.connect(Socket.java:589)
[Lobby-1][07:50:07 WARN]:       at java.net.Socket.connect(Socket.java:538)
[Lobby-1][07:50:07 WARN]:       at java.net.Socket.<init>(Socket.java:434)
[Lobby-1][07:50:07 WARN]:       at java.net.Socket.<init>(Socket.java:211)
[Lobby-1][07:50:07 WARN]:       at com.github.theholywaffle.teamspeak3.FileTransferHelper.uploadFile(FileTransferHelper.java:94)
[Lobby-1][07:50:07 WARN]:       at com.github.theholywaffle.teamspeak3.TS3ApiAsync.lambda$uploadFile$26(TS3ApiAsync.java:5090)
[Lobby-1][07:50:07 WARN]:       at com.github.theholywaffle.teamspeak3.api.CommandFuture.set(CommandFuture.java:479)
[Lobby-1][07:50:07 WARN]:       at com.github.theholywaffle.teamspeak3.api.CommandFuture.lambda$map$0(CommandFuture.java:690)
[Lobby-1][07:50:07 WARN]:       at com.github.theholywaffle.teamspeak3.api.CommandFuture.set(CommandFuture.java:479)
[Lobby-1][07:50:07 WARN]:       at com.github.theholywaffle.teamspeak3.SocketReader.lambda$handleCommandError$0(SocketReader.java:166)
[Lobby-1][07:50:07 WARN]:       ... 6 more

```

**Comment by rogermb** [comment]
Hi @Angxstupst

Here's how file transfers work in the TS3 server query interface:
1. First, we send a command to the server telling it that we want to upload or download a file
2. The server responds with an IP and a port number that we're supposed to use for the file transfer
3. We connect to that IP and port and upload / download the file from there.

What's going wrong here is step 3: For some reason, you're not able to connect to the IP and port that the TS3 server sends you.

So to fix your issue, you need to first figure out what port the TS3 server wants to use for file transfers (usually 30033), for example by turning on command logging and reading the server's response to the `ftinitupload` command, and then figuring out why you're not able to connect to it. Perhaps you just need to add port forwarding for port 30033 or something like that 😃
