### ISSUE TITLE
Timeout value is negative

### ISSUE THREAD

**Issue by ahmadsakr** [TheHolyWaffle/TeamSpeak-3-Java-API#41]
After a while, the keep alive thread sleep time becomes negative.

Exception in thread "[TeamSpeak-3-Java-API] Keep alive" java.lang.IllegalArgumentException: timeout value is negative
	at java.lang.Thread.sleep(Native Method)
	at com.github.theholywaffle.teamspeak3.KeepAliveThread.run(KeepAliveThread.java:53)

**Comment by Firedroide** [comment]
Yup, I made a mistake implementing the timeouts.
Basically, the timeout will currently be negative no matter what.

Fixed in 2b3cb84fc2684997793952e52d9a306bb6221234.
Thank you very much for reporting this. If any other issue should come up, feel free to report them :)

**Comment by TheVonLeon** [comment]
I'm getting this with the latest snapshot.
http://pastebin.com/ZhW6JJ71
