### ISSUE TITLE
java.lang.NoClassDefFoundError: com/github/theholywaffle/teamspeak3/TS3Config

### ISSUE THREAD

**Issue by Captainthrills** [TheHolyWaffle/TeamSpeak-3-Java-API#62]
Exception in thread "main" java.lang.NoClassDefFoundError: com/github/theholywaffle/teamspeak3/TS3Config
	    at test.TS3Bot.main(TS3Bot.java:18)
    Caused by: java.lang.ClassNotFoundException: com.github.theholywaffle.teamspeak3.TS3Config
	    at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
	    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	    at java.security.AccessController.doPrivileged(Native Method)
	    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	    at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	    at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	    ... 1 more

Snippet:
```
package test;

import java.util.Arrays;
import java.util.List;

import com.github.theholywaffle.teamspeak3.TS3Api;
import com.github.theholywaffle.teamspeak3.TS3Config;
import com.github.theholywaffle.teamspeak3.TS3Query;
import com.github.theholywaffle.teamspeak3.api.TextMessageTargetMode;
import com.github.theholywaffle.teamspeak3.api.event.TS3EventAdapter;
import com.github.theholywaffle.teamspeak3.api.event.TS3EventType;
import com.github.theholywaffle.teamspeak3.api.event.TextMessageEvent;

public class TS3Bot {
	
	public static void main(String[] args){
		
		final TS3Config config = new TS3Config();                 //<----- Here
		config.setHost("127.0.0.1");
		config.setLoginCredentials("admin", "password");
		
		final TS3Query query = new TS3Query(config);
		query.connect();
```
Build Path Jar File:
`teamspeak3-api-1.0.12.jar`

**Comment by Kakifrucht** [comment]
You need to compile the api into your compiled file.
https://github.com/TheHolyWaffle/TeamSpeak-3-Java-API/issues/61

**Comment by Captainthrills** [comment]
Damn looks like I'll have to mess with maven hell again.

**Comment by Captainthrills** [comment]
All cleared up now.
