### ISSUE TITLE
sendtextmessage is not answered in time issue.

### ISSUE THREAD

**Issue by LeoStoch** [TheHolyWaffle/TeamSpeak-3-Java-API#81]
I dont know if it is an issue, but I have a problem with my bot. I get after a few minutes/moments this errors:

> [02:22:04] [Thread-660/WARN]: [DEBUG] [SEVERE] Command sendtextmessage is not answered in time.
[02:22:05] [Thread-662/WARN]: [DEBUG] [SEVERE] Command sendtextmessage is not answered in time.
[02:22:08] [Thread-670/WARN]: [DEBUG] [SEVERE] Command sendtextmessage is not answered in time.
[02:22:14] [Thread-682/WARN]: [DEBUG] [SEVERE] Command sendtextmessage is not answered in time.
[02:22:15] [Thread-684/WARN]: [DEBUG] [SEVERE] Command sendtextmessage is not answered in time.
[02:22:15] [Thread-686/WARN]: [DEBUG] [SEVERE] Command sendtextmessage is not answered in time.
[02:22:20] [Thread-696/WARN]: [DEBUG] [SEVERE] Command sendtextmessage is not answered in time.
[02:22:26] [Thread-710/WARN]: [DEBUG] [SEVERE] Command sendtextmessage is not answered in time.
[02:22:27] [Thread-712/WARN]: [DEBUG] [SEVERE] Command sendtextmessage is not answered in time.
[02:22:27] [Thread-714/WARN]: [DEBUG] [SEVERE] Command sendtextmessage is not answered in time.
[02:22:28] [Thread-715/WARN]: [DEBUG] [SEVERE] Command sendtextmessage is not answered in time.
[02:22:28] [Thread-716/WARN]: [DEBUG] [SEVERE] Command sendtextmessage is not answered in time.
[02:22:31] [Thread-722/WARN]: [DEBUG] [SEVERE] Command sendtextmessage is not answered in time.
[02:22:31] [Thread-723/WARN]: [DEBUG] [SEVERE] Command sendtextmessage is not answered in time.
[02:22:36] [Thread-734/WARN]: [DEBUG] [SEVERE] Command sendtextmessage is not answered in time.
[02:22:41] [Thread-746/WARN]: [DEBUG] [SEVERE] Command sendtextmessage is not answered in time.
[02:22:42] [Thread-747/WARN]: [DEBUG] [SEVERE] Command sendtextmessage is not answered in time.
[02:22:42] [Thread-748/WARN]: [DEBUG] [SEVERE] Command sendtextmessage is not answered in time.
[02:22:42] [Thread-749/WARN]: [DEBUG] [SEVERE] Command sendtextmessage is not answered in time.

everything else is still working but strongly lagging. I use nothing that send so often a text message. Any ideas how to fix it

**Comment by Firedroide** [comment]
First of all, I see that you're on a pretty old version of the API.

Please use [the latest release](http://theholywaffle.github.io/TeamSpeak-3-Java-API/download.html) or use one of the newer snapshots from the [the Frankenstein Maven repository](https://github.com/TheHolyWaffle/TeamSpeak-3-Java-API/tree/mvn-repo).

If this problem still occurs, it might be due to a wrong `FloodRate` setting in `TS3Config`.
You can only use `ULTIMATE` = 50ms/command if the IP used by your query is whitelisted on the TS3 server. Otherwise, you must use `DEFAULT` = 350ms/command, or else the server will ban you for sending commands too rapidly. This would produce the exact behavior you're describing.

If that's also not what's causing your problems, I'd like you to send me a) a bit more of the log, especially what happens immediately before your problems arise (setting the logger level to `DEBUG` also produces more output) and b) send me the snippet of code that you think is responsible.

I hope your bug-hunt is successful :)

**Comment by LeoStoch** [comment]
With the newest version I get directly after starting the error messages. With the older one it happened after a few hours of working. I added the server IP to the TS3 whitelist and set the floodrate to default.
I set the logger level to all.

> [14:44:49] [Query Listener #1/INFO]: Query running on 85.190.134.253:25565
[14:44:53] [Timer-1/INFO]: [2016-02-12 14:44:53.155] [SEVERE] Command channelinfo was not answered in time.
[14:44:53] [Timer-1/WARN]: Exception in thread "Timer-1" 
[14:44:53] [Timer-1/WARN]: java.lang.NullPointerException
[14:44:53] [Timer-1/WARN]: 	at me.TS.channeledit$1.run(channeledit.java:52)
[14:44:53] [Timer-1/WARN]: 	at java.util.TimerThread.mainLoop(Timer.java:555)
[14:44:53] [Timer-1/WARN]: 	at java.util.TimerThread.run(Timer.java:505)
[14:44:53] [pool-9-thread-1/INFO]: [2016-02-12 14:44:53.385] [SEVERE] Command sendtextmessage was not answered in time.
[14:45:44] [Timer-2/INFO]: [2016-02-12 14:45:44.048] [SEVERE] Command clientlist was not answered in time.
[14:45:44] [Timer-2/WARN]: Exception in thread "Timer-2" 
[14:45:44] [Timer-2/WARN]: java.lang.NullPointerException
[14:45:44] [Timer-2/WARN]: 	at me.TS.Points$1$1.run(Points.java:39)
[14:45:44] [Timer-2/WARN]: 	at java.util.TimerThread.mainLoop(Timer.java:555)
[14:45:44] [Timer-2/WARN]: 	at java.util.TimerThread.run(Timer.java:505)
[14:45:44] [Timer-3/INFO]: [2016-02-12 14:45:44.055] [SEVERE] Command clientlist was not answered in time.
[14:45:44] [Timer-3/WARN]: Exception in thread "Timer-3" 
[14:45:44] [Timer-3/WARN]: java.lang.NullPointerException
[14:45:44] [Timer-3/WARN]: 	at me.TS.afkmover$1$1.run(afkmover.java:28)
[14:45:44] [Timer-3/WARN]: 	at java.util.TimerThread.mainLoop(Timer.java:555)
[14:45:44] [Timer-3/WARN]: 	at java.util.TimerThread.run(Timer.java:505)
[14:45:44] [pool-9-thread-3/INFO]: [2016-02-12 14:45:44.218] [SEVERE] Command sendtextmessage was not answered in time.
[14:49:51] [pool-9-thread-2/INFO]: [2016-02-12 14:49:51.312] [SEVERE] Command sendtextmessage was not answered in time.
[14:49:51] [pool-9-thread-1/INFO]: [2016-02-12 14:49:51.412] [SEVERE] Command sendtextmessage was not answered in time.
[14:49:51] [pool-9-thread-2/INFO]: [2016-02-12 14:49:51.772] [SEVERE] Command sendtextmessage was not answered in time.
[14:49:52] [pool-9-thread-1/INFO]: [2016-02-12 14:49:52.128] [SEVERE] Command sendtextmessage was not answered in time.
[14:49:52] [pool-9-thread-2/INFO]: [2016-02-12 14:49:52.485] [SEVERE] Command sendtextmessage was not answered in time.
[14:49:52] [pool-9-thread-1/INFO]: [2016-02-12 14:49:52.835] [SEVERE] Command sendtextmessage was not answered in time.
[14:49:53] [pool-9-thread-2/INFO]: [2016-02-12 14:49:53.195] [SEVERE] Command sendtextmessage was not answered in time.
[14:49:53] [pool-9-thread-1/INFO]: [2016-02-12 14:49:53.552] [SEVERE] Command sendtextmessage was not answered in time.
[14:49:53] [pool-9-thread-2/INFO]: [2016-02-12 14:49:53.902] [SEVERE] Command sendtextmessage was not answered in time.
[14:49:54] [pool-9-thread-1/INFO]: [2016-02-12 14:49:54.255] [SEVERE] Command sendtextmessage was not answered in time.
[14:49:54] [pool-9-thread-2/INFO]: [2016-02-12 14:49:54.608] [SEVERE] Command sendtextmessage was not answered in time.
[14:49:54] [pool-9-thread-1/INFO]: [2016-02-12 14:49:54.965] [SEVERE] Command sendtextmessage was not answered in time.
[14:49:55] [pool-9-thread-2/INFO]: [2016-02-12 14:49:55.315] [SEVERE] Command sendtextmessage was not answered in time.
[14:49:55] [pool-9-thread-1/INFO]: [2016-02-12 14:49:55.672] [SEVERE] Command sendtextmessage was not answered in time.
[14:49:56] [pool-9-thread-2/INFO]: [2016-02-12 14:49:56.028] [SEVERE] Command sendtextmessage was not answered in time.
[14:49:56] [pool-9-thread-1/INFO]: [2016-02-12 14:49:56.385] [SEVERE] Command sendtextmessage was not answered in time.
[14:49:56] [pool-9-thread-2/INFO]: [2016-02-12 14:49:56.738] [SEVERE] Command sendtextmessage was not answered in time.
[14:49:57] [pool-9-thread-1/INFO]: [2016-02-12 14:49:57.092] [SEVERE] Command sendtextmessage was not answered in time.
[14:49:57] [pool-9-thread-2/INFO]: [2016-02-12 14:49:57.452] [SEVERE] Command sendtextmessage was not answered in time.
[14:49:57] [pool-9-thread-1/INFO]: [2016-02-12 14:49:57.808] [SEVERE] Command sendtextmessage was not answered in time.
[14:49:58] [pool-9-thread-2/INFO]: [2016-02-12 14:49:58.162] [SEVERE] Command sendtextmessage was not answered in time.
[14:49:58] [pool-9-thread-1/INFO]: [2016-02-12 14:49:58.522] [SEVERE] Command sendtextmessage was not answered in time.
[14:49:58] [pool-9-thread-2/INFO]: [2016-02-12 14:49:58.878] [SEVERE] Command sendtextmessage was not answered in time.
[14:49:59] [pool-9-thread-1/INFO]: [2016-02-12 14:49:59.235] [SEVERE] Command sendtextmessage was not answered in time.
[14:49:59] [pool-9-thread-2/INFO]: [2016-02-12 14:49:59.590] [SEVERE] Command sendtextmessage was not answered in time.
[14:49:59] [pool-9-thread-1/INFO]: [2016-02-12 14:49:59.942] [SEVERE] Command sendtextmessage was not answered in time.
[14:50:00] [pool-9-thread-2/INFO]: [2016-02-12 14:50:00.302] [SEVERE] Command sendtextmessage was not answered in time.
[14:50:00] [pool-9-thread-1/INFO]: [2016-02-12 14:50:00.658] [SEVERE] Command sendtextmessage was not answered in time.
[14:50:01] [pool-9-thread-2/INFO]: [2016-02-12 14:50:01.015] [SEVERE] Command sendtextmessage was not answered in time.
[14:50:01] [pool-9-thread-1/INFO]: [2016-02-12 14:50:01.368] [SEVERE] Command sendtextmessage was not answered in time.
[14:50:01] [pool-9-thread-2/INFO]: [2016-02-12 14:50:01.728] [SEVERE] Command sendtextmessage was not answered in time.
[14:50:02] [pool-9-thread-1/INFO]: [2016-02-12 14:50:02.085] [SEVERE] Command sendtextmessage was not answered in time.
[14:50:02] [pool-9-thread-2/INFO]: [2016-02-12 14:50:02.438] [SEVERE] Command sendtextmessage was not answered in time.
[14:50:02] [pool-9-thread-1/INFO]: [2016-02-12 14:50:02.795] [SEVERE] Command sendtextmessage was not answered in time.
[14:50:03] [pool-9-thread-2/INFO]: [2016-02-12 14:50:03.152] [SEVERE] Command sendtextmessage was not answered in time.
[14:50:03] [pool-9-thread-1/INFO]: [2016-02-12 14:50:03.508] [SEVERE] Command sendtextmessage was not answered in time.
[14:50:03] [pool-9-thread-2/INFO]: [2016-02-12 14:50:03.862] [SEVERE] Command sendtextmessage was not answered in time.
[14:50:04] [pool-9-thread-1/INFO]: [2016-02-12 14:50:04.218] [SEVERE] Command sendtextmessage was not answered in time.
[14:50:04] [pool-9-thread-2/INFO]: [2016-02-12 14:50:04.568] [SEVERE] Command sendtextmessage was not answered in time.
[14:50:04] [pool-9-thread-1/INFO]: [2016-02-12 14:50:04.925] [SEVERE] Command sendtextmessage was not answered in time.
[14:50:05] [pool-9-thread-2/INFO]: [2016-02-12 14:50:05.282] [SEVERE] Command sendtextmessage was not answered in time.
[14:50:05] [pool-9-thread-1/INFO]: [2016-02-12 14:50:05.638] [SEVERE] Command sendtextmessage was not answered in time.
[14:50:05] [pool-9-thread-2/INFO]: [2016-02-12 14:50:05.995] [SEVERE] Command sendtextmessage was not answered in time.
[14:50:06] [pool-9-thread-1/INFO]: [2016-02-12 14:50:06.348] [SEVERE] Command sendtextmessage was not answered in time.
[14:50:06] [pool-9-thread-2/INFO]: [2016-02-12 14:50:06.702] [SEVERE] Command sendtextmessage was not answered in time.
[14:50:07] [pool-9-thread-1/INFO]: [2016-02-12 14:50:07.058] [SEVERE] Command sendtextmessage was not answered in time.
[14:50:07] [pool-9-thread-2/INFO]: [2016-02-12 14:50:07.418] [SEVERE] Command sendtextmessage was not answered in time.
[14:50:07] [pool-9-thread-1/INFO]: [2016-02-12 14:50:07.772] [SEVERE] Command sendtextmessage was not answered in time.
[14:50:08] [pool-9-thread-2/INFO]: [2016-02-12 14:50:08.132] [SEVERE] Command sendtextmessage was not answered in time.
[14:50:08] [pool-9-thread-1/INFO]: [2016-02-12 14:50:08.485] [SEVERE] Command sendtextmessage was not answered in time.
[14:50:08] [pool-9-thread-2/INFO]: [2016-02-12 14:50:08.835] [SEVERE] Command sendtextmessage was not answered in time.
[14:50:09] [pool-9-thread-1/INFO]: [2016-02-12 14:50:09.195] [SEVERE] Command sendtextmessage was not answered in time.
[14:50:09] [pool-9-thread-2/INFO]: [2016-02-12 14:50:09.552] [SEVERE] Command sendtextmessage was not answered in time.
[14:50:09] [pool-9-thread-1/INFO]: [2016-02-12 14:50:09.904] [SEVERE] Command sendtextmessage was not answered in time.
[14:50:10] [pool-9-thread-2/INFO]: [2016-02-12 14:50:10.262] [SEVERE] Command sendtextmessage was not answered in time.
[14:50:10] [pool-9-thread-1/INFO]: [2016-02-12 14:50:10.618] [SEVERE] Command sendtextmessage was not answered in time.
[14:50:10] [pool-9-thread-2/INFO]: [2016-02-12 14:50:10.972] [SEVERE] Command sendtextmessage was not answered in time.
[14:50:11] [pool-9-thread-1/INFO]: [2016-02-12 14:50:11.328] [SEVERE] Command sendtextmessage was not answered in time.
[14:50:11] [pool-9-thread-2/INFO]: [2016-02-12 14:50:11.688] [SEVERE] Command sendtextmessage was not answered in time.
[14:50:12] [pool-9-thread-1/INFO]: [2016-02-12 14:50:12.045] [SEVERE] Command sendtextmessage was not answered in time.
[14:50:12] [pool-9-thread-2/INFO]: [2016-02-12 14:50:12.398] [SEVERE] Command sendtextmessage was not answered in time.
[14:50:12] [pool-9-thread-1/INFO]: [2016-02-12 14:50:12.755] [SEVERE] Command sendtextmessage was not answered in time.
[14:50:13] [pool-9-thread-2/INFO]: [2016-02-12 14:50:13.112] [SEVERE] Command sendtextmessage was not answered in time.
[14:50:13] [pool-9-thread-1/INFO]: [2016-02-12 14:50:13.465] [SEVERE] Command sendtextmessage was not answered in time.
[14:50:13] [pool-9-thread-2/INFO]: [2016-02-12 14:50:13.818] [SEVERE] Command sendtextmessage was not answered in time.
[14:50:14] [pool-9-thread-1/INFO]: [2016-02-12 14:50:14.168] [SEVERE] Command sendtextmessage was not answered in time.
[14:50:14] [pool-9-thread-2/INFO]: [2016-02-12 14:50:14.525] [SEVERE] Command sendtextmessage was not answered in time.
[14:50:14] [pool-9-thread-1/INFO]: [2016-02-12 14:50:14.882] [SEVERE] Command sendtextmessage was not answered in time.
[14:50:15] [pool-9-thread-2/INFO]: [2016-02-12 14:50:15.242] [SEVERE] Command sendtextmessage was not answered in time.
[14:50:15] [pool-9-thread-1/INFO]: [2016-02-12 14:50:15.598] [SEVERE] Command sendtextmessage was not answered in time.
[14:50:15] [pool-9-thread-2/INFO]: [2016-02-12 14:50:15.952] [SEVERE] Command sendtextmessage was not answered in time.
[14:50:16] [pool-9-thread-1/INFO]: [2016-02-12 14:50:16.305] [SEVERE] Command sendtextmessage was not answered in time.
[14:50:16] [pool-9-thread-2/INFO]: [2016-02-12 14:50:16.662] [SEVERE] Command sendtextmessage was not answered in time.
[14:50:17] [pool-9-thread-1/INFO]: [2016-02-12 14:50:17.022] [SEVERE] Command sendtextmessage was not answered in time.
[14:50:17] [pool-9-thread-2/INFO]: [2016-02-12 14:50:17.378] [SEVERE] Command sendtextmessage was not answered in time.
[14:50:17] [pool-9-thread-1/INFO]: [2016-02-12 14:50:17.728] [SEVERE] Command sendtextmessage was not answered in time.
[14:50:18] [pool-9-thread-2/INFO]: [2016-02-12 14:50:18.085] [SEVERE] Command sendtextmessage was not answered in time.
[14:50:18] [pool-9-thread-1/INFO]: [2016-02-12 14:50:18.442] [SEVERE] Command sendtextmessage was not answered in time.
[14:50:18] [pool-9-thread-2/INFO]: [2016-02-12 14:50:18.802] [SEVERE] Command sendtextmessage was not answered in time.
[14:50:19] [pool-9-thread-1/INFO]: [2016-02-12 14:50:19.158] [SEVERE] Command sendtextmessage was not answered in time.
[14:50:19] [pool-9-thread-2/INFO]: [2016-02-12 14:50:19.508] [SEVERE] Command sendtextmessage was not answered in time.
[14:50:19] [pool-9-thread-1/INFO]: [2016-02-12 14:50:19.862] [SEVERE] Command sendtextmessage was not answered in time.
[14:50:20] [pool-9-thread-2/INFO]: [2016-02-12 14:50:20.218] [SEVERE] Command sendtextmessage was not answered in time.
[14:50:20] [pool-9-thread-1/INFO]: [2016-02-12 14:50:20.575] [SEVERE] Command sendtextmessage was not answered in time.
[14:50:20] [pool-9-thread-2/INFO]: [2016-02-12 14:50:20.932] [SEVERE] Command sendtextmessage was not answered in time.
[14:50:21] [pool-9-thread-1/INFO]: [2016-02-12 14:50:21.285] [SEVERE] Command sendtextmessage was not answered in time.
[14:50:21] [pool-9-thread-2/INFO]: [2016-02-12 14:50:21.635] [SEVERE] Command sendtextmessage was not answered in time.
[14:50:21] [pool-9-thread-1/INFO]: [2016-02-12 14:50:21.992] [SEVERE] Command sendtextmessage was not answered in time.
[14:50:22] [pool-9-thread-2/INFO]: [2016-02-12 14:50:22.348] [SEVERE] Command sendtextmessage was not answered in time.
[14:50:22] [pool-9-thread-1/INFO]: [2016-02-12 14:50:22.698] [SEVERE] Command sendtextmessage was not answered in time.
[14:50:23] [pool-9-thread-2/INFO]: [2016-02-12 14:50:23.052] [SEVERE] Command sendtextmessage was not answered in time.
[14:50:23] [pool-9-thread-1/INFO]: [2016-02-12 14:50:23.412] [SEVERE] Command sendtextmessage was not answered in time.
[14:50:23] [pool-9-thread-2/INFO]: [2016-02-12 14:50:23.768] [SEVERE] Command sendtextmessage was not answered in time.
[14:50:24] [pool-9-thread-1/INFO]: [2016-02-12 14:50:24.122] [SEVERE] Command sendtextmessage was not answered in time.
[14:50:24] [pool-9-thread-2/INFO]: [2016-02-12 14:50:24.478] [SEVERE] Command sendtextmessage was not answered in time.

**Comment by Firedroide** [comment]
I wonder, why is the actual IO not included in your log? Usually it should be, unless you re-routed it to a log file, that is ^^

But what I think is quite likely is that you're currently banned from the TS server but not noticing it. I might have to do something about that :stuck_out_tongue:

**Comment by LeoStoch** [comment]
I am using this on a minecraft server. Maybe cause of this. But why am I getting banned after a few commands? I added the server to the whitelist and I get the welcomemessage and a few commands are still working. Something like Clientinfo is not working or Clientlist but sending simple messages is possible.

**Comment by Firedroide** [comment]
I am honestly not sure. Testing your plugin locally would be a great idea to start imo.

I can't really say much else without seeing the actual commands and responses. Your code might also give insight as to why it isn't working.

**Comment by LeoStoch** [comment]
I think it is the fault of a repeating task. I have 3 differents:
`	public static void mover(){
		Bukkit.getScheduler().runTaskAsynchronously(Mainclass.getInstance(), new Runnable() {

			@Override
			public void run() {			
				  boolean punktes=true;
					Timer timer = new Timer();
					TS3Api ts = Mainclass.connecting();
					timer.schedule(new TimerTask(){
						Channel channels = ts.getChannelByNameExact("AFK", true);
						int afktime=3600000;
						public void run() {
							if(punktes==true){				
							for(Client punkte: ts.getClients()){
								if(!(punkte.getChannelId()==ts.getChannelByNameExact("Musik-Channel", true).getId())){
									
								
								if(punkte.getIdleTime()>= afktime){
										if(punkte.getChannelId()!=channels.getId()){
											ts.moveClient(punkte.getId(), channels.getId());
										}
									}else if(punkte.isOutputMuted() || punkte.isInputMuted() || punkte.isAway()){
										if(punkte.getChannelId() != channels.getId()){
										if(punkte.isAway()){
											ts.moveClient(punkte.getId(), channels.getId());
										}else if(punkte.getIdleTime()>=600000){
											ts.moveClient(punkte.getId(), channels.getId());

										}
										
									}}
								}}
						}}},1000,10000);}});
			  }`

`public static void edit(){
				  HashMap<ChannelProperty, String> map = new HashMap<ChannelProperty, String>();
					TS3Api ts = Mainclass.connecting();
					int max = Bukkit.getMaxPlayers();
					Timer timer = new Timer();
					timer.schedule(new TimerTask(){
						public void run() {
							String names = "";
							String clients = Mainclass.getClients();
							int Player = Bukkit.getOnlinePlayers().size();
							for(Player pl: Bukkit.getOnlinePlayers()){
								if(pl.hasPermission("ts.list.owner")){
									names = "[img]https://minotar.net/avatar/"+pl.getName()+"/16[/img] [b][color=Darkviolet][[/color][color=Maroon]Owner[/color][color=Darkviolet]][/color] "+pl.getName()+"\n"+names;

								}else if(pl.hasPermission("ts.list.admin")){
									names = "[img]https://minotar.net/avatar/"+pl.getName()+"/16[/img] [b][color=Darkviolet][[/color][color=red]Admin[/color][color=Darkviolet]][/color] "+pl.getName()+"\n"+names;

								}else if(pl.hasPermission("ts.list.moderator")){
									
									names = "[img]https://minotar.net/avatar/"+pl.getName()+"/16[/img] [b][color=Darkviolet][[/color][color=Darkmagenta]Moderator[/color][color=Darkviolet]][/color] "+pl.getName()+"\n"+names;

								}else if(pl.hasPermission("ts.list.supporter")){
									names = "[img]https://minotar.net/avatar/"+pl.getName()+"/16[/img] [b][color=Darkviolet][[/color][color=Steelblue]Supporter[/color][color=Darkviolet]][/color] "+pl.getName()+"\n"+names;

								}else if(pl.hasPermission("ts.list.architekt")){
									names = "[img]https://minotar.net/avatar/"+pl.getName()+"/16[/img] [b][color=Darkviolet][[/color][color=Orange]Architekt[/color][color=Darkviolet]][/color] "+pl.getName()+"\n"+names;

								}else{
									names = "[img]https://minotar.net/avatar/"+pl.getName()+"/16[/img] [b][color=Darkviolet][[/color][color=green]Spieler[/color][color=Darkviolet]][/color] "+pl.getName()+"\n"+names;

								}
							}
							if(!(ts.getChannelInfo(1534).getDescription().equals(names+"\n\n\n[b]"+Player+"[/b]/[b]"+max+"[/b] Players are online.")) || !(ts.getChannelInfo(1534).getName().equals("[cspacer555]Minecraft: [" +Player+"/"+ max+"]"))){
								if(!(ts.getChannelInfo(1534).getName().equals("[cspacer555]Minecraft [" +Player+"/"+ max+"]"))){
									map.put(ChannelProperty.CHANNEL_NAME, "[cspacer555]Minecraft: [" +Player+"/"+ max+"]");
								}
								map.put(ChannelProperty.CHANNEL_DESCRIPTION, names+"\n\n\n[b]"+Player+"[/b]/[b]"+max+"[/b] Players are online.");
								map.put(ChannelProperty.CHANNEL_TOPIC, "Minecraft Player Information");
								ts.editChannel(1534, map);
								names = "";
								map.clear();
							}
							
						for(Client p: ts.getClients()){
							if(!(p.getNickname().equals(Mainclass.getInstance().getConfig().getString("Config.teamspeak.server.botname")))){
								clients = ChatColor.GRAY+p.getNickname()+"\n"+clients;
							}
							
						}

						}},1000,2000);
			  }`
and `public static void Punkte(){
				  boolean punkte=true;
					Timer timer = new Timer();
					TS3Api ts = Mainclass.connecting();
					timer.schedule(new TimerTask(){
						Channel channels = ts.getChannelByNameExact("AFK", punkte);
						int idletime = 20000;
						public void run() {
							if(punkte==true){				
							for(Client punkte: ts.getClients()){
								if(punkte.getIdleTime()<= idletime){
									if(punkte.getChannelId()!=channels.getId()){
										int get = SQLMethods.SQLActionLevel(punkte.getUniqueIdentifier());
										double Punkte = 1;
										if(!(get<=1)){
											Punkte = get*1.25;
										}
										BigDecimal g = new BigDecimal(Punkte);
										g = g.setScale(2, BigDecimal.ROUND_CEILING);
										try {
											Statement s = SQL.sqlconnecting().createStatement();
											s.execute("update TsTable SET onlinetime = onlinetime+1 where UUID='"+punkte.getUniqueIdentifier()+"';");
											s.close();
										} catch (SQLException e) {
											// TODO Auto-generated catch block
											e.printStackTrace();
										}
									}
									}
								}
						}}},1000,60000);
			  
		
		}`

**Comment by Firedroide** [comment]
## TS3 Api Usage

```java
    if(!(punkte.getChannelId()==ts.getChannelByNameExact("Musik-Channel", true).getId())){
```

Cache that ID, please, instead of doing a query command for each iteration of the loop.

```java
for(Client p: ts.getClients()){
    if(!(p.getNickname().equals(Mainclass.getInstance().getConfig().getString("Config.teamspeak.server.botname")))){
        clients = ChatColor.GRAY+p.getNickname()+"\n"+clients;
    }
}
```

You can search for clients by nickname.

```java
    if(!(ts.getChannelInfo(1534).getDescription().equals(names+"\n\n\n[b]"+Player+"[/b]/[b]"+max+"[/b] Players are online.")) || !(ts.getChannelInfo(1534).getName().equals("[cspacer555]Minecraft: [" +Player+"/"+ max+"]"))){
        if(!(ts.getChannelInfo(1534).getName().equals("[cspacer555]Minecraft [" +Player+"/"+ max+"]"))){
```

You're calling `ts.getChannelInfo(1534)` 3 times when you'd just need to call it once. All methods in TS3Api and TS3ApiAsync **take time to execute**. This is just completely useless overhead.
Also, spaghetti code.

## SQL

```java
try {
    Statement s = SQL.sqlconnecting().createStatement();
    s.execute("update TsTable SET onlinetime = onlinetime+1 where UUID='"+punkte.getUniqueIdentifier()+"';");
    s.close();
} catch (SQLException e) {
    // TODO Auto-generated catch block
    e.printStackTrace();
}
```

Unclosed `Statement` in case of an exception. Use a `finally` block or use a `try-with-resources` (google it).
Also, if `sqlconnecting()` (camelCase in Java, please) opens a new connection, you must close that one, as well.

```java
s.execute("update TsTable SET onlinetime = onlinetime+1 where UUID='"+punkte.getUniqueIdentifier()+"';");
```

In this case not really a security risk, but generally **this causes SQL injection attacks!**
Use prepared statements!! Java has such good support for them.

## Plain Old Java WTFs

```java
if(!(get<=1)){
```

Seriously?
`if (get > 1) {`

```java
if(punkte==true){
```

`if (punkte) {`

```java
if(punkte==true){
    for(Client punkte: ts.getClients()) {
        if(punkte.getIdleTime()<= idletime){
            if(punkte.getChannelId()!=channels.getId()){
```

How about
```
if (!punkte) return;

for(Client punkte : ts.getClients()) {
    if (punkte.getIdleTime() > idletime) continue;
    if (punkte.getChannelId() == channels.getId()) continue;
```
Tell the code what to do. If "punkte" is not true, escape. If "x" is not met, continue, etc.
Don't build these giant code blocks with little meaning.

```java
if(!(p.getNickname().equals(Mainclass.getInstance().getConfig().getString("Config.teamspeak.server.botname")))){
```

Way too much complexity in one `if` statement. Reduce it, add local variables, etc.

```java
    HashMap<ChannelProperty, String> map = new HashMap<ChannelProperty, String>();
```

Use the "diamond operator".
`HashMap<ChannelProperty, String> map = new HashMap<>();`

```java
public static void Punkte(){
    Timer timer = new Timer();
```

Are you kidding me?? You're creating a new `Timer` every time that function is called? Seriously a bad idea. Moreover, you don't even need to create threads on your own! Bukkit has a task scheduler you can and **should** use!

```java
=== THE ENTIRE THING ===
```

Use the automatic formatting tool to make your code look better. I think it's `Ctrl + Shift + F` in Eclipse.

> I think it is the fault of a repeating task.

This and code that just has not been thought through at all.
The things I just pointed out were just the most superficial problems I found when skimming through this code. Think before you code. I know you can do so much better.

**Comment by LeoStoch** [comment]
You are completly right, I wrote this code last night while Iw as tired. I sould rework the whole code. But thanks for you help.

**Comment by Firedroide** [comment]
Yeah, sorry for the quite harsh "code review" :sweat:
Coding is hard and a lot of it is learning-by-doing. Stay on it and keep improving your code :smile:

I think what would help your code (and your coding) the most is to embrace the object oriented design paradigm.
Currently, you're only using static methods and not much would change if classes didn't even exist. A side effect of that is that you get exactly these huge, hard-to-read and hard-to-maintain methods. Try limiting the scope of each class to one specific area.

Just as an example (and probably a bad one at that), you could create a package called "database" and have a class for each table. That way you'd group similar functions together and you'd have limited your scope.

**Comment by LeoStoch** [comment]
Anyway...I reworked the code and found the most stupid mistake that can happen :laughing: 
I had for `config.setCommandTimeout();` the value 40 inserted xD

**Comment by Firedroide** [comment]
Ah, alright :D

If any other issues arise, feel free to reopen this issue, create a new one or just ask us directly over at [Gitter](https://gitter.im/TheHolyWaffle/TeamSpeak-3-Java-API).

Thanks for the quick responses!
