### ISSUE TITLE
SocketReader: java.util.concurrent.RejectedExecutionException on TS3Query#exit();

### ISSUE THREAD

**Issue by Scrumplex** [TheHolyWaffle/TeamSpeak-3-Java-API#98]
Hello there!
```
Exception in thread "[TeamSpeak-3-Java-API] SocketReader" java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.FutureTask@1a0f4e0f rejected from java.util.concurrent.ThreadPoolExecutor@28088fbc[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 73]
        at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2047)
        at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:823)
        at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1369)
        at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)
        at com.github.theholywaffle.teamspeak3.TS3Query.fireDisconnect(TS3Query.java:200)
        at com.github.theholywaffle.teamspeak3.SocketReader.run(SocketReader.java:128)
```
I sometimes get the exception above when exiting my application. As far as I understood the the code, `TS3Query#fireDisconnect()`gets executed after the `ScheduledExecutorService` has been shut down.

Kind regards
Sefa E.

**Comment by Firedroide** [comment]
Sorry for not answering for so long; the problem you're reporting has been known for quite a bit of time and fortunately only exists in snapshot builds.

It is caused by me haphazardly adding a still bleeding-edge reconnect feature and not doing the necessary checks when firing the disconnect handler. Fortunately, though, this bug doesn't really screw anything up, it just prints this lovely message to the console. That's also the reason why I never really bothered to fix the bug.

Anyways, I'll mostly rewrite the reconnect system soon-ish anyways, which should also fix this issue.
Nevertheless, thank you very much for reporting this here. I don't always encounter all these bugs, which is why it's crucial that they're brought to my attention :smile:

**Comment by Firedroide** [comment]
https://github.com/TheHolyWaffle/TeamSpeak-3-Java-API/commit/313a8c7ff7a7c8820158b17537c309cd3b4c771f should fix this.
If you get any issues in the new version, please feel free to re-open this issue.
Thanks again for your contributions to this API :smile:
